
import java.util.Date;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class MainMenu extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public static String uname, pass;
    boolean btn = false, data = false, ticket = false;

    String frm, to, time, buscode, nm, email, dt, asit;
    int tk;

    public MainMenu() {
        initComponents();
        con = AppSetting.ConnectDT();
        this.setLocationRelativeTo(null);
        buttonpnl.setVisible(false);
        dataviewpnl.setVisible(false);
        allbtnpnl.setPreferredSize(new Dimension(153, 520));
        Show();
    }

    private void Show() {
        String sql = "Select name,email from user_info where username=?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, uname);
            rs = pst.executeQuery();
            if (rs.next()) {
                nm = rs.getString(1);
                email = rs.getString(2);

            } else {
                JOptionPane.showMessageDialog(null, "Username doesn't match");
            }
            con.close();
            BuyTicket.Nameis(nm, email);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public static void Check(String str, String str2) {
        uname = str;
        pass = str2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        allbtnpnl = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        settingbtn = new javax.swing.JButton();
        buttonpnl = new javax.swing.JPanel();
        editprofilebtn = new javax.swing.JButton();
        changepasswordbtn = new javax.swing.JButton();
        deleteaccountbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromtxt = new javax.swing.JTextField();
        totxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DATE = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dataviewpnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datagridview = new javax.swing.JTable();
        ticketbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 150, 136));

        jLabelClose.setBackground(new java.awt.Color(255, 255, 255));
        jLabelClose.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("x");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMin.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 76));

        jPanel5.setBackground(new java.awt.Color(51, 51, 76));

        jPanel7.setBackground(new java.awt.Color(51, 51, 76));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        allbtnpnl.setBackground(new java.awt.Color(28, 71, 77));

        logoutbtn.setBackground(new java.awt.Color(219, 88, 96));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("LogOut");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        profilebtn.setBackground(new java.awt.Color(22, 160, 133));
        profilebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilebtn.setForeground(new java.awt.Color(255, 255, 255));
        profilebtn.setText("Profile");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });

        settingbtn.setBackground(new java.awt.Color(22, 160, 133));
        settingbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        settingbtn.setForeground(new java.awt.Color(255, 255, 255));
        settingbtn.setText("Setting");
        settingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingbtnActionPerformed(evt);
            }
        });

        buttonpnl.setBackground(new java.awt.Color(50, 63, 79));

        editprofilebtn.setBackground(new java.awt.Color(22, 160, 133));
        editprofilebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editprofilebtn.setForeground(new java.awt.Color(255, 255, 255));
        editprofilebtn.setText("Edit Profile");
        editprofilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofilebtnActionPerformed(evt);
            }
        });

        changepasswordbtn.setBackground(new java.awt.Color(22, 160, 133));
        changepasswordbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changepasswordbtn.setForeground(new java.awt.Color(255, 255, 255));
        changepasswordbtn.setText("Change Password");
        changepasswordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordbtnActionPerformed(evt);
            }
        });

        deleteaccountbtn.setBackground(new java.awt.Color(22, 160, 133));
        deleteaccountbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteaccountbtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteaccountbtn.setText("Delete Account");
        deleteaccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteaccountbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonpnlLayout = new javax.swing.GroupLayout(buttonpnl);
        buttonpnl.setLayout(buttonpnlLayout);
        buttonpnlLayout.setHorizontalGroup(
            buttonpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editprofilebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changepasswordbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
            .addComponent(deleteaccountbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonpnlLayout.setVerticalGroup(
            buttonpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpnlLayout.createSequentialGroup()
                .addComponent(editprofilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changepasswordbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteaccountbtn)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        buttonpnlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changepasswordbtn, deleteaccountbtn, editprofilebtn});

        javax.swing.GroupLayout allbtnpnlLayout = new javax.swing.GroupLayout(allbtnpnl);
        allbtnpnl.setLayout(allbtnpnlLayout);
        allbtnpnlLayout.setHorizontalGroup(
            allbtnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allbtnpnlLayout.createSequentialGroup()
                .addGroup(allbtnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(settingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        allbtnpnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {profilebtn, settingbtn});

        allbtnpnlLayout.setVerticalGroup(
            allbtnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allbtnpnlLayout.createSequentialGroup()
                .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        allbtnpnlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {profilebtn, settingbtn});

        jPanel6.setBackground(new java.awt.Color(51, 51, 76));
        jPanel6.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(51, 51, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 252, 245));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CITY TRANSPORT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 252, 245));
        jLabel2.setText("From");

        fromtxt.setBackground(new java.awt.Color(108, 122, 137));
        fromtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromtxt.setForeground(new java.awt.Color(228, 241, 254));
        fromtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fromtxtMouseClicked(evt);
            }
        });

        totxt.setBackground(new java.awt.Color(108, 122, 137));
        totxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totxt.setForeground(new java.awt.Color(228, 241, 254));
        totxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totxtMouseClicked(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(22, 160, 133));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("SearcH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 252, 245));
        jLabel4.setText("To");

        DATE.setDateFormatString("MM-dd-yyyy");
        DATE.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 252, 245));
        jLabel3.setText("Date");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fromtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(totxt)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(searchbtn)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(fromtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchbtn)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel8);
        jPanel8.setBounds(0, 0, 650, 320);

        dataviewpnl.setBackground(new java.awt.Color(51, 51, 76));

        datagridview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datagridview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datagridviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datagridview);

        ticketbtn.setBackground(new java.awt.Color(22, 160, 133));
        ticketbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ticketbtn.setForeground(new java.awt.Color(255, 255, 255));
        ticketbtn.setText("Buy Ticket");
        ticketbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataviewpnlLayout = new javax.swing.GroupLayout(dataviewpnl);
        dataviewpnl.setLayout(dataviewpnlLayout);
        dataviewpnlLayout.setHorizontalGroup(
            dataviewpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(dataviewpnlLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(ticketbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataviewpnlLayout.setVerticalGroup(
            dataviewpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataviewpnlLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ticketbtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(dataviewpnl);
        dataviewpnl.setBounds(0, 320, 650, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(allbtnpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allbtnpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void settingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingbtnActionPerformed
        if (btn) {
            buttonpnl.setVisible(false);
            btn = false;
        } else {
            buttonpnl.setVisible(true);
            btn = true;
        }
    }//GEN-LAST:event_settingbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM-dd-yyyy");
        LocalDateTime now = LocalDateTime.now();

        dt = ((JTextField) DATE.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat datef = new SimpleDateFormat("MM-dd-yyyy");
        String dtt = (dtf.format(now));
        try {
            Date d1 = datef.parse(dt);
            Date d2 = datef.parse(dtt);
            if (d1.compareTo(d2) < 0) {
                JOptionPane.showMessageDialog(null, "Please select present or future dates..");
            } else {
                if (!fromtxt.getText().isEmpty() && !totxt.getText().isEmpty()) {
                    con = AppSetting.ConnectDT();
                    String sql = "SELECT route.from_where, route.to_where, route.fare, route.time,route.bus_code, bus_info.available_sit"
                            + " FROM route INNER JOIN bus_info ON route.bus_code = bus_info.bus_code WHERE from_where = ? AND to_where = ?";
                    try {
                        pst = con.prepareStatement(sql);
                        pst.setString(1, fromtxt.getText());
                        pst.setString(2, totxt.getText());
                        rs = pst.executeQuery();
                        datagridview.setModel(DbUtils.resultSetToTableModel(rs));
                        con.close();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                    dataviewpnl.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Enter your terminal and destination");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select present or future date");
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void fromtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromtxtMouseClicked
        dataviewpnl.setVisible(false);
    }//GEN-LAST:event_fromtxtMouseClicked

    private void totxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totxtMouseClicked
        dataviewpnl.setVisible(false);
    }//GEN-LAST:event_totxtMouseClicked

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        ShowProfile.Check(uname);
        ShowProfile.Code(0);
        ShowProfile sp = new ShowProfile();

        sp.setVisible(true);
    }//GEN-LAST:event_profilebtnActionPerformed

    private void editprofilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofilebtnActionPerformed
        ShowProfile.Check(uname);
        ShowProfile.Code(1);
        ShowProfile sp = new ShowProfile();
        sp.setVisible(true);
    }//GEN-LAST:event_editprofilebtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        LoginPanel l = new LoginPanel();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    
    private void deleteaccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteaccountbtnActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure want to delete your account ?", "Delete Account", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            con = AppSetting.ConnectDT();
            String sql = "Delete from user_info where username=?";
            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, uname);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Account Deleted");
                con.close();
                LoginPanel l = new LoginPanel();
                l.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_deleteaccountbtnActionPerformed

    private void changepasswordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordbtnActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure want to change your password ?", "Change Password", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            ChangePassword.Check(uname, pass);
            ChangePassword cp = new ChangePassword();
            cp.setVisible(true);

        }
    }//GEN-LAST:event_changepasswordbtnActionPerformed

    private void datagridviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datagridviewMouseClicked
        ticket = true;
        DefaultTableModel model = (DefaultTableModel) datagridview.getModel();
        int Myindex = datagridview.getSelectedRow();
        frm = (model.getValueAt(Myindex, 0).toString());
        to = (model.getValueAt(Myindex, 1).toString());
        tk = Integer.parseInt(model.getValueAt(Myindex, 2).toString());
        time = (model.getValueAt(Myindex, 3).toString());
        buscode = (model.getValueAt(Myindex, 4).toString());
        asit = (model.getValueAt(Myindex, 5).toString());
    }//GEN-LAST:event_datagridviewMouseClicked

    private void ticketbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketbtnActionPerformed
        if (ticket) {
            BuyTicket.Fill(frm, to, time, tk, buscode, dt, asit);
            BuyTicket bt = new BuyTicket();
            bt.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Select a row please...");
        }
    }//GEN-LAST:event_ticketbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DATE;
    private javax.swing.JPanel allbtnpnl;
    private javax.swing.JPanel buttonpnl;
    private javax.swing.JButton changepasswordbtn;
    private javax.swing.JTable datagridview;
    private javax.swing.JPanel dataviewpnl;
    private javax.swing.JButton deleteaccountbtn;
    private javax.swing.JButton editprofilebtn;
    private javax.swing.JTextField fromtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton profilebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton settingbtn;
    private javax.swing.JButton ticketbtn;
    private javax.swing.JTextField totxt;
    // End of variables declaration//GEN-END:variables
}
