
import java.awt.Dimension;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ShowProfile extends javax.swing.JFrame {

    static int cd = -1;
    String nm = null, unm = null, email = null, gen = null, gend = null;
    String imageName = null;
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    static String uname = null;

    public ShowProfile() {
        initComponents();
        jPanel1.setPreferredSize(new Dimension(437, 490));
        if (cd == 0) {
            updatebtn.setVisible(false);
            femalebtn.setVisible(false);
        } else if (cd == 1) {
            updatebtn.setVisible(true);
            femalebtn.setVisible(true);
        }
        con = AppSetting.ConnectDT();
        this.setLocationRelativeTo(null);
        Show();

    }

    public static void Code(int x) {
        cd = x;
    }

    public static void Check(String str) {
        uname = str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        malebtn = new javax.swing.JRadioButton();
        updatebtn = new javax.swing.JButton();
        femalebtn = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabelClose4 = new javax.swing.JLabel();
        jLabelMin4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 76));
        setBounds(new java.awt.Rectangle(0, 0, 350, 250));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 76));

        pic.setBackground(new java.awt.Color(255, 255, 255));
        pic.setForeground(new java.awt.Color(255, 255, 255));
        pic.setText("j");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Name");

        nametxt.setBackground(new java.awt.Color(108, 122, 137));
        nametxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nametxt.setForeground(new java.awt.Color(228, 241, 254));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Username");

        usernametxt.setBackground(new java.awt.Color(108, 122, 137));
        usernametxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(228, 241, 254));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Email");

        emailtxt.setBackground(new java.awt.Color(108, 122, 137));
        emailtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(228, 241, 254));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Gender");

        malebtn.setBackground(new java.awt.Color(51, 51, 76));
        malebtn.setForeground(new java.awt.Color(236, 240, 241));
        malebtn.setSelected(true);
        malebtn.setText("Male");
        malebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malebtnMouseClicked(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(0, 150, 136));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        femalebtn.setBackground(new java.awt.Color(51, 51, 76));
        femalebtn.setForeground(new java.awt.Color(236, 240, 241));
        femalebtn.setText("Female");
        femalebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femalebtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(malebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(femalebtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pic)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malebtn)
                    .addComponent(femalebtn))
                .addGap(27, 27, 27)
                .addComponent(updatebtn)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 150, 136));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabelClose4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelClose4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelClose4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose4.setText("x");
        jLabelClose4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose4MouseClicked(evt);
            }
        });

        jLabelMin4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMin4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelMin4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin4.setText("-");
        jLabelMin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelClose4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClose4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelClose4MouseClicked

    private void jLabelMin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMin4MouseClicked

    private void malebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malebtnMouseClicked
        gen = "Male";
        malebtn.setSelected(true);
        femalebtn.setSelected(false);
        try {
            if (gen == "Male") {
                imageName = "E:\\UI_DESIGN\\male.png";
            } else {
                imageName = "E:\\UI_DESIGN\\female.png";
            }
            pic.setIcon(new ImageIcon(ImageIO.read(new File(imageName))));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not found!!!");
        }
    }//GEN-LAST:event_malebtnMouseClicked

    private void femalebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femalebtnMouseClicked
        gen = "Female";
        malebtn.setSelected(false);
        try {
            if (gen == "Male") {
                imageName = "E:\\UI_DESIGN\\male.png";
            } else {
                imageName = "E:\\UI_DESIGN\\female.png";
            }
            pic.setIcon(new ImageIcon(ImageIO.read(new File(imageName))));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not found!!!");
        }
    }//GEN-LAST:event_femalebtnMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        if (nametxt.getText().isEmpty() && usernametxt.getText().isEmpty() && emailtxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Infromation is not valid!!");
        } else if (nametxt.getText().equalsIgnoreCase(nm) && usernametxt.getText().equalsIgnoreCase(unm) && emailtxt.getText().equalsIgnoreCase(email) && gend.equalsIgnoreCase(gen)) {
            JOptionPane.showMessageDialog(null, "Change your infromation to update");
        } else {
            con = AppSetting.ConnectDT();
            String v1 = nametxt.getText();
            String v2 = usernametxt.getText();
            String v3 = emailtxt.getText();

            String sql = "Update user_info set name=?,username=?,email=?,gender=? where username=?";

            try {
                pst = con.prepareStatement(sql);
                pst.setString(1, v1);
                pst.setString(2, v2);
                pst.setString(3, v3);
                pst.setString(4, gen);
                pst.setString(5, uname);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Infromation Updated");
                con.close();
                
                MainMenu.uname = v2;
                uname=v2;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton femalebtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose4;
    private javax.swing.JLabel jLabelMin4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton malebtn;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel pic;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables

    private void Show() {
        con = AppSetting.ConnectDT();
        String sql = "Select name,username,email,gender from user_info where username=?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, uname);
            rs = pst.executeQuery();
            if (rs.next()) {
                nm = rs.getString(1);
                nametxt.setText(rs.getString(1));

                usernametxt.setText(rs.getString(2));
                unm = rs.getString(2);

                email = rs.getString(3);
                emailtxt.setText(rs.getString(3));

                gen = rs.getString(4);

                gend = gen;

                try {
                    if (gen.equalsIgnoreCase("Male")) {
                        imageName = "E:\\UI_DESIGN\\male.png";
                    } else {
                        imageName = "E:\\UI_DESIGN\\female.png";
                    }
                    pic.setIcon(new ImageIcon(ImageIO.read(new File(imageName))));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "File not found!!!");
                }
                if (cd == 0) {
                    nametxt.setEditable(false);
                    usernametxt.setEditable(false);
                    emailtxt.setEditable(false);
                    malebtn.setText(gen);
                } else if (cd == 1) {
                    nametxt.setEditable(true);
                    usernametxt.setEditable(true);
                    emailtxt.setEditable(true);
                    malebtn.setText("Male");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username doesn't match");
            }
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
}
